export enum ModeType {
  DARK_MODE = 'DARK_MODE',
  OPEN_SETTINGS = 'OPEN_SETTINGS',
  HEADER_MENU = 'HEADER_MENU',
  TOGGLE_DRAWER = 'TOGGLE_DRAWER',
  LEFT_MENU = 'LEFT_MENU',
  CLOSE_ALL = 'CLOSE_ALL',
}

export enum GithubType {
  GITHUB_REPO_REQUEST = 'GITHUB_REPO_REQUEST',
  GITHUB_REPO_REQUEST_SUCCESS = 'GITHUB_REPO_REQUEST_SUCCESS',
  GITHUB_REPO_REQUEST_FAIL = 'GITHUB_REPO_REQUEST_FAIL',
}

// const DARK_MODE = 'DARK_MODE';
// const OPEN_SETTINGS = 'OPEN_SETTINGS';
// const HEADER_MENU = 'HEADER_MENU';
// const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
// const LEFT_MENU = 'LEFT_MENU';
// const CLOSE_ALL = 'CLOSE_ALL';

// const GITHUB_REPO_REQUEST = 'GITHUB_REPO_REQUEST';
// const GITHUB_REPO_REQUEST_SUCCESS = 'GITHUB_REPO_REQUEST_SUCCESS';
// const GITHUB_REPO_REQUEST_FAIL = 'GITHUB_REPO_REQUEST_FAIL';

// export {
//   DARK_MODE,
//   OPEN_SETTINGS,
//   HEADER_MENU,
//   TOGGLE_DRAWER,
//   LEFT_MENU,
//   CLOSE_ALL,
//   GITHUB_REPO_REQUEST_FAIL,
//   GITHUB_REPO_REQUEST,
//   GITHUB_REPO_REQUEST_SUCCESS,
// };
