export enum ModeType {
  DARK_MODE = 'DARK_MODE',
  OPEN_SETTINGS = 'OPEN_SETTINGS',
  HEADER_MENU = 'HEADER_MENU',
  TOGGLE_DRAWER = 'TOGGLE_DRAWER',
  LEFT_MENU = 'LEFT_MENU',
  CLOSE_ALL = 'CLOSE_ALL',
}

export enum GithubType {
  GITHUB_REPO_REQUEST = 'GITHUB_REPO_REQUEST',
  GITHUB_REPO_REQUEST_SUCCESS = 'GITHUB_REPO_REQUEST_SUCCESS',
  GITHUB_REPO_REQUEST_FAIL = 'GITHUB_REPO_REQUEST_FAIL',
}
